@skillsetName = skillset-sharepoint-demo-index-53

###
PUT https://llmdevcog001.search.windows.net/skillsets/{{skillsetName}}?api-version=2020-06-30
Content-Type: application/json  
api-key: {{$dotenv AZURE_SEARCH_ADMIN_KEY}}  

{
  "name": "{{skillsetName}}",
  "description": "Built-in AI skills.",
  "skills": [
    {
      "@odata.type": "#Microsoft.Skills.Text.V3.EntityRecognitionSkill",
      "name": "#1",
      "description": null,
      "context": "/document/page",
      "categories": [
        "Organization",
        "Person",
        "Location"
      ],
      "defaultLanguageCode": "en",
      "minimumPrecision": null,
      "modelVersion": null,
      "inputs": [
        {
          "name": "text",
          "source": "/document/page"
        }
      ],
      "outputs": [
        {
          "name": "organizations",
          "targetName": "organizations"
        },
        {
          "name": "persons",
          "targetName": "persons"
        },
        {
          "name": "locations",
          "targetName": "locations"
        }
      ]
    },
    {
      "@odata.type": "#Microsoft.Skills.Text.KeyPhraseExtractionSkill",
      "name": "#2",
      "description": null,
      "context": "/document/page",
      "defaultLanguageCode": "en",
      "maxKeyPhraseCount": null,
      "modelVersion": null,
      "inputs": [
        {
          "name": "text",
          "source": "/document/page"
        },
        {
          "name": "languageCode",
          "source": "/document/language"
        }
      ],
      "outputs": [
        {
          "name": "keyPhrases",
          "targetName": "keyPhrases"
        }
      ]
    }
  ],
  "cognitiveServices": {
    "@odata.type": "#Microsoft.Azure.Search.CognitiveServicesByKey",
    "description": "{{$dotenv AZURE_COGNITIVE_ACCOUNT_RESOURCE}}",
    "key": "{{$dotenv AZURE_COGNITIVE_ACCOUNT_KEY}}"
  },
  "knowledgeStore": null,
  "encryptionKey": null
}